name: Intro to CI

on:
    push:

env:
    NAME: Thibaut

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - run: echo "Hello ${{ env.NAME}}"
            
            - uses: pnpm/action-setup@v2.4.0
              name: Install pnpm
              with:
                version: 8
                run_install: false

            - name: Get pnpm store directory
              shell: bash
              run: |
                echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

            - uses: actions/cache@v3
              name: Setup pnpm cache
              with:
                path: ${{ env.STORE_PATH }}
                key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                restore-keys: |
                    ${{ runner.os }}-pnpm-store-
            
            - name: Install dependencies
              run: pnpm install
            
            - name: Build
              run: pnpm run build

            - name: Run the server
              run: |
                pnpm run preview &
                sleep 5
                
            - name: Test with curl
              run: |
                curl -I http://localhost:4173